In [1]:
import numpy as np

## Practice

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.


In [2]:
#1
arr1 = np.zeros((10, 10))
arr1[0] = np.ones((1, 10))
arr1[-1] = np.ones((1, 10))
arr1[::, 0] = 1.0
arr1[::, -1] = 1.0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [3]:
#2
# arr2 = np.array([np.arange(0, 5, 1) for _ in range(5)])
# arr2

arr2 = np.tile(np.arange(0, 5, 1), (5, 1))
arr2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [4]:
#3
# arr3 = np.zeros((8, 8))
# arr3[::2, 1::2] = 1.0
# arr3[1::2, ::2] = 1.0
# arr3

arr3 = np.tile([[0,1],[1,0]],(4,4))
arr3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [5]:
#4
def odd(arr):
    return arr[arr%2==1]

arr4 = np.array([0,1,2,3,4,5,6,7,8,9])
odd(arr4)

array([1, 3, 5, 7, 9])

5. Normalize a 5x5 random matrix 

In [6]:
#5
arr5 = np.random.random((5,5))
arr5 = (arr5 - np.mean (arr5)) / (np.std (arr5))
arr5

array([[-0.54386845, -1.15155043, -0.2331505 ,  0.62100897, -0.08854576],
       [-1.572823  ,  0.41660973, -1.53349854,  1.21024813, -1.65094166],
       [ 1.02454567,  1.45098942,  0.88995174,  0.95850046,  1.31878158],
       [ 0.82735486, -0.36836131, -0.85821728,  0.29662018, -0.12132123],
       [-0.85026428,  1.08977668,  1.04405572, -0.85481305, -1.32108767]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [7]:
#6
Z = np.random.rand(10, 2)
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y, X)
print(f'X={X},\nY={Y},\nR={R},\nT={T}')

X=[0.1030305  0.40456086 0.37732673 0.21141742 0.5207786  0.74858767
 0.87711999 0.76356876 0.4959808  0.14209462],
Y=[0.26566621 0.1726509  0.51550813 0.59758107 0.53312423 0.73877135
 0.20834194 0.14335885 0.60908016 0.67464942],
R=[0.2849453  0.43986114 0.63884591 0.63387732 0.74527297 1.05174455
 0.90152418 0.77690991 0.78547795 0.68945103],
T=[1.20083439 0.4033615  0.93894694 1.23075028 0.79711183 0.77879843
 0.2332078  0.18558795 0.88738975 1.36321045]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [8]:
#7
vec = np.array([1,2,3,4,5], dtype=int)
arr4 = np.zeros(len(vec)*4, dtype=int)
arr4[::4] = vec
arr4

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [9]:
#8
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


9. What are the result of the following expressions? (Hint: the type of np.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [10]:
#9
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-10-3ef312c5d1e0>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-10-3ef312c5d1e0>:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
