In [2]:
import numpy as np
DIRECTIONS = np.array([[0,1], [0,-1], [1,0], [-1,0], [1,1], [1,-1], [-1,1], [-1,-1]])
COLOR_NONE = 0
[1,2]+DIRECTIONS

array([[1, 3],
       [1, 1],
       [2, 2],
       [0, 2],
       [2, 3],
       [2, 1],
       [0, 3],
       [0, 1]])

In [25]:
board = np.array([
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, -1, 1, 0, 0, 0],
        [0, 0, 0, 1, -1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]
    ])
board[3,3]

-1

In [11]:
import numpy as np
def flip_chess(chessboard: np.ndarray, color, pos) -> None:
    in_chessboard = (lambda idx: (idx[0] in range(len(chessboard)) and idx[1] in range(len(chessboard))))
    
    chesses = np.argwhere((chessboard==color))
    chess_to_flip = []
    for chess in chesses:
        dis = pos - chess
        cur = chess
        if dis[0] != 0 and dis[1] != 0:
            if abs(dis[0]) != abs(dis[1]):
                continue
        tmp_flip = []
        times = abs(dis[0]) if dis[0] != 0 else abs(dis[1])
        step = dis // times
        for i in range(1, times+1):
            tmp_flip.append(i*step + cur)
        if len(tmp_flip) > 0:
            chess_to_flip.append(tmp_flip)
    
    for flip_list in chess_to_flip:
        for chess_pos in flip_list:
            chessboard[chess_pos[0], chess_pos[1]] = color

In [7]:
a = np.array([3,4])
b = np.array([1,2])
(a-b)//2

array([1, 1], dtype=int32)

In [2]:
board = np.array([
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]
    ])
flip_chess(board, 1, [5,6])

NameError: name 'flip_chess' is not defined

In [13]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
import numpy as np
board = np.array([
        [1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]
    ])
Vmap = np.array([[500,-25,10,5,5,10,-25,500],
                    [-25,-45,1,1,1,1,-45,-25],
                    [10,1,3,2,2,3,1,10],
                    [5,1,2,1,1,2,1,5],
                    [5,1,2,1,1,2,1,5],
                    [10,1,3,2,2,3,1,10],
                    [-25,-45,1,1,1,1,-45,-25],
                    [500,-25,10,5,5,10,-25,500]])


sum(sum(board*Vmap))

501

In [30]:
COLOR_NONE = 0
def valid_moves(chessboard: np.ndarray, color):
    """
        找到所有可能的有效下棋位置
    Params:
        chessboard: np.ndarray,      棋盘
        color: int                   棋子颜色
    Return:
        moves: List[List[int, int]]  所有可能的有效下棋位置
    """
    moves = []
    chesses = np.argwhere(chessboard == color)
    none_area = np.argwhere(chessboard == COLOR_NONE)
    
    for pos in none_area:
        # flag用来保证越过了其他颜色的棋子
        flag = False
        for chess in chesses:
            dis = chess - pos
            if dis[0] != 0 and dis[1] != 0:
                if abs(dis[0]) != abs(dis[1]):
                    continue
            times = abs(dis[0]) if dis[0] != 0 else abs(dis[1])
            step = dis // times
            # 不会到达chess的位置
            for i in range(1, times):
                now_pos = i*step + pos
                if chessboard[now_pos[0], now_pos[1]] == -color:
                    flag = True
                else: # 遇到空处或者提前遇到己方棋子，不算有效
                    flag = False
                    break
            if flag: # 找到就溜
                moves.append(pos)
                break

    return moves

In [48]:
chessboard_size = 8
COLOR_NONE = 0
def in_chessboard(idx) -> bool:
    return idx[0] >= 0 and idx[0] < chessboard_size and idx[1] >= 0 and idx[1] < chessboard_size
def stable_value(chessboard: np.ndarray, color):
    stable = [0, 0, 0]  # 角，边，中心。中心的稳定子只计算了部分
    stable_pos = set()  # 角、边的稳定子
    corners = [(0, 0), (0, 7), (7, 0), (7, 7)]
    direc1 = [(1, 0), (0, -1), (0, 1), (-1, 0)]
    direc2 = [(0, 1), (1, 0), (-1, 0), (0, -1)]
    for i in range(4):
        cor: tuple = corners[i]
        # 角
        if chessboard[cor[0], cor[1]] == color:
            stable[0] += 1
            # 边，两个方向
            for j in range(1, 7):
                pos = (cor[0]+j*direc1[i][0], cor[1]+j*direc1[i][1])
                if chessboard[pos[0], pos[1]] == color:
                    stable[1] += 1
                    stable_pos.add(pos)
                else:
                    break
            for j in range(1, 7):
                pos = (cor[0]+j*direc2[i][0], cor[1]+j*direc2[i][1])
                if chessboard[pos[0], pos[1]] == color:
                    stable[1] += 1
                    stable_pos.add(pos)
                else:
                    break
    inner_stable = np.zeros((8, 8), dtype=bool)
    inner_stable[:, np.sum(abs(chessboard), axis=0) == 8] = True  # 列
    inner_stable[np.sum(abs(chessboard), axis=1) == 8, :] &= True  # 行
    # 斜线
    inner_stable_chess = np.argwhere(inner_stable == True)
    diag_direc = [(1, 1), (1, -1), (-1, 1), (-1, -1)]

    if len(inner_stable) == 0:
        return stable

    for chess in inner_stable_chess:
        if (chess[0], chess[1]) in stable_pos:
            continue
        for dd in diag_direc:
            pos = chess + dd
            flag = False
            while in_chessboard(pos):
                if chessboard[pos[0], pos[1]] == COLOR_NONE:
                    inner_stable[chess[0], chess[1]] = False
                    flag = True
                    break
                pos += dd
            if flag:
                break
                
    stable[2] = sum(sum(inner_stable))
    return stable

In [49]:
import numpy as np
board = np.array([
        [1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [0, -1, -1, 0, 0, 0, 0, 0],
        [0, -1, 1, 1, 1, 0, 0, 0],
        [0, -1, 1, -1, -1, 0, 0, 0],
        [0, -1, 1, 0, 0, 1, 0, 0],
        [0, -1, -1, 0, 0, 0, 1, 0],
        [0, -1, 1, 0, 0, 0, 0, -1]
    ])
stable_value(board, 1)

[1, 3, 2]

In [32]:
np.array([1,2])+(1,2)

array([2, 4])

In [31]:
board = np.array([
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, -1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, -1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]
    ])

valid_moves(board, -1)

[array([2, 4], dtype=int64),
 array([4, 2], dtype=int64),
 array([7, 7], dtype=int64)]

In [23]:
a = set()
a.add((0,1))
a.add((0,1))

In [2]:
b = None
b is not None

False

In [4]:
first_moves  = [[0,1], [0,-1], [1,0], [-1,0], [1,1], [1,-1], [-1,1], [-1,-1]]
list(map(lambda idx: (idx[0], idx[1]), first_moves))

[(0, 1), (0, -1), (1, 0), (-1, 0), (1, 1), (1, -1), (-1, 1), (-1, -1)]

In [4]:
las = ['123.jpg', '234.jpg', '024.jpg', '010.jpg', '009.jpg']
las.sort()
# las.sort(key=lambda x: int())
las

['009.jpg', '010.jpg', '024.jpg', '123.jpg', '234.jpg']

In [ ]:
file = open('sa','wb')
file.write

In [4]:
class Node:
    def __init__(self, color, parent=None, action=None):
        self.color: int = color
        self.parent = parent
        self.children = {}
        self.Q: int = 0 # 价值
        self.N: int = 0 # 访问次数

n1 = Node(1)
n2 = Node(-1)
n3 = Node(-1)
n4 = Node(-1)
n5 = Node(-1)
n6 = Node(-1)

for x, y, n in [[0,1, n2], [0,-1,n3], [1,0,n4], [-1,0,n5], [1,1,n6]]:
    n1.children[n] = (x,y)

In [5]:
chromosomes = ['AGCTACTGACTG', 'ACCGACTG']
GC_content = [0 for _ in range(len(chromosomes))]

for i, chromo in enumerate(chromosomes):
    c_cnt = chromo.count('C')
    g_cnt = chromo.count('G')
    GC_content[i] = (c_cnt + g_cnt) / len(chromo)

ORF_st = 'AUG'
ORF_ed = ['UAA', 'UAG', 'UGA']
ORF_cnt = [0 for _ in range(len(chromosomes))]
for i, chromo in enumerate(chromosomes):
    for j in range(0, len(chromo), 3):
        codon = chromo[j: j+3]
        if codon in ORF_ed:
            ORF_cnt[i] += 1


HBB = 'ACTGAGTCA'
HBB_pos = [0 for _ in range(len(chromosomes))]
for i, chromo in enumerate(chromosomes):
    HBB_pos[i] = chromo.find(HBB)

In [3]:
import numpy as np

a = np.array([
    [1,5,3,3,3,3,5,1],
    [5,5,4,4,4,4,5,5],
    [3,4,2,2,2,2,4,3],
    [3,4,2,0,0,2,4,3],
    [3,4,2,0,0,2,4,3],
    [3,4,2,2,2,2,4,3],
    [5,5,4,4,4,4,5,5],
    [1,5,3,3,3,3,5,1],
]).shape

(8, 8)

In [ ]:
import time
print('Start ...')
print('next move is (2,3)')
print('time taken ')